import { Vertical } from "./experts";

export const VERTICAL_TO_TOPICS: Record<Vertical, string[]> = {
  product: ["ai-product", "management-leadership", "decision-making", "customer-research"],
  engineering: ["vibe-coding", "ai-agents", "rag-llm-apps", "claude-code", "ai-evals"],
  data: ["ai-analysis", "ai-evals", "rag-llm-apps", "decision-making"],
  design: ["ai-design", "ux-design", "figma-design-systems", "vibe-coding"],
  marketing: ["ai-marketing", "personal-branding", "gtm-engineering", "communication-storytelling"],
  sales: ["gtm-engineering", "ai-for-sales", "communication-storytelling"],
  ops: ["ai-productivity", "ai-x-leaders", "management-leadership", "decision-making"],
  founder: ["vibe-coding", "ai-agents", "ai-product", "ai-productivity", "gtm-engineering"],
};

export interface LightningLesson {
  id: string;
  title: string;
  slug: string;
  instructorName: string;
  instructorTitle: string;
  instructorImg: string;
  isUpcoming: boolean;
  startDate: string | null;
  topics: string[];
}

export const LESSONS: LightningLesson[] = [
  {
    id: "ll-353f4f",
    title: "No Vibes, Just Evals: Proven Frameworks for AI-Native PMs",
    slug: "353f4f",
    instructorName: "Jason P. Yoong",
    instructorTitle: "Co-Founder & COO at Level Up (Prev: Amazon, Dentsu, IPG, Startup - $8M seed)",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/dLFZIdjQRtCjHkIRBKtf_JPY%20Photo.png",
    isUpcoming: true,
    startDate: "2026-03-20T16:30:00-04:00",
    topics: ["ai-evals"],
  },
  {
    id: "ll-3704a5",
    title: "Executive Presence for Poor Public Speakers",
    slug: "3704a5",
    instructorName: "Ethan Evans",
    instructorTitle: "Former Amazon VP (15+ years); 70+ patents; led global teams of 800+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/wdXOug3XRQS6FAyUb5le_Ethan%20Evans%20Photo%201.jpeg",
    isUpcoming: true,
    startDate: "2026-04-01T14:00:00-04:00",
    topics: ["communication-storytelling"],
  },
  {
    id: "ll-9c40d3",
    title: "Building Conversational AI Products with Alexa+ PM lead)",
    slug: "9c40d3",
    instructorName: "Dr. Marily Nika",
    instructorTitle: "Gen AI PM Lead @ Google | ex-Meta, Fellow @ Harvard | TED AI Speaker | 40u40",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/pSuhPzFyTmbEtsDy5rUY_marily-nika.jpeg",
    isUpcoming: true,
    startDate: "2026-04-01T15:00:00-04:00",
    topics: ["ai-product"],
  },
  {
    id: "ll-a10eac",
    title: "Build ANY world-class AI product in hours, not months",
    slug: "a10eac",
    instructorName: "Paweł Huryn",
    instructorTitle: "Author of the #1 AI & Product Newsletter | AI Agents & Architecture Expert",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/5XwKwj84TVmNNlcyCKRR_1718237240033.jpg",
    isUpcoming: true,
    startDate: "2026-04-09T12:00:00-04:00",
    topics: ["ai-product"],
  },
  {
    id: "ll-f69472",
    title: "The 100× Product Builder: Become the Claude Code Architect!",
    slug: "f69472",
    instructorName: "Carl Vellotti",
    instructorTitle: "Creator of Viral AI workflows for PMs | Writing \"The Full Stack PM\"",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/hsDkTZMLRmmiwI45brLr_unnamed-1.jpg",
    isUpcoming: true,
    startDate: "2026-03-26T13:00:00-04:00",
    topics: ["claude-code"],
  },
  {
    id: "ll-470e97",
    title: "Building AI Agents: Bootcamp 2603 Public Demo",
    slug: "470e97",
    instructorName: "Amir Feizpour",
    instructorTitle: "Founder @ Aggregate Intellect",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/9vtg7pbbTfeJWrBnLDz3_me_green.jpeg",
    isUpcoming: true,
    startDate: "2026-05-01T12:00:00-04:00",
    topics: ["ai-agents"],
  },
  {
    id: "ll-4594fc",
    title: "Agentic Long Loop Workflows That Solve Real Problems",
    slug: "4594fc",
    instructorName: "Amir Feizpour",
    instructorTitle: "Founder @ Aggregate Intellect",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/9vtg7pbbTfeJWrBnLDz3_me_green.jpeg",
    isUpcoming: true,
    startDate: "2026-03-27T12:00:00-04:00",
    topics: ["ai-agents"],
  },
  {
    id: "ll-a1c760",
    title: "Synthetic Users for Product Discovery: What People Miss",
    slug: "a1c760",
    instructorName: "Caitlin Sullivan",
    instructorTitle: "Ex-Head of UXR, Spotify Business/Soundtrack ᐧ Advisor ᐧ AI Customer Research",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/ZEkLDi3eSdewKnoT5twJ_Caitlin%20Sullivan%20Profile%20-%20AI%20for%20User%20Research%20copy.jpeg",
    isUpcoming: true,
    startDate: "2026-03-26T09:30:00-04:00",
    topics: ["customer-research"],
  },
  {
    id: "ll-a605d8",
    title: "Get Answers In Hours With AI-Powered Customer Interviews",
    slug: "a605d8",
    instructorName: "John Whalen, PhD",
    instructorTitle: "AI for UX Expert, Fortune 100 clientele, CEO, author & speaker",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/UlZS8fyJR0uNqka13d1L_John-04.jpg",
    isUpcoming: true,
    startDate: "2026-04-29T17:00:00-04:00",
    topics: ["customer-research"],
  },
  {
    id: "ll-c93ea6",
    title: "How PMs Stay Irreplaceable as AI Changes Project Management",
    slug: "c93ea6",
    instructorName: "Justin Bateh, PhD",
    instructorTitle: "CEO | 25,000+ learners | 80+ Projects | 8x Awards | LinkedIn Learning Instructor",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/4cpU9KsBRwq6I6DzPzts_Untitled%20(800%20x%20800%20px)%20(800%20x%20800%20px)%20(LinkedIn%20Profile%20Picture).png",
    isUpcoming: true,
    startDate: "2026-03-30T11:00:00-04:00",
    topics: ["management-leadership"],
  },
  {
    id: "ll-e8f2c6",
    title: "How to Vibe Code an AI App Using Lovable",
    slug: "e8f2c6",
    instructorName: "Manu Jayawardana",
    instructorTitle: "AI Founder | 35K-User Fintech Exit | Co-Founder Snapdrum | Trained 5,000+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/7nm90orSQyMT2ivDci7B_HUx7egtLRnyuHnAGDSQc_manuuuuu.webp",
    isUpcoming: true,
    startDate: "2026-03-21T18:00:00-04:00",
    topics: ["vibe-coding"],
  },
  {
    id: "ll-f69fbf",
    title: "Build a Simple AI Operations Dashboard Using Lovable",
    slug: "f69fbf",
    instructorName: "Manu Jayawardana",
    instructorTitle: "AI Founder | 35K-User Fintech Exit | Co-Founder Snapdrum | Trained 5,000+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/3JCPRQgzRcGWdpDuNatK_HUx7egtLRnyuHnAGDSQc_manuuuuu%20(1).webp",
    isUpcoming: true,
    startDate: "2026-03-21T18:00:00-04:00",
    topics: ["vibe-coding"],
  },
  {
    id: "ll-f5aa54",
    title: "How Founders and PMs Can Prototype AI Products Fast",
    slug: "f5aa54",
    instructorName: "Manu Jayawardana",
    instructorTitle: "AI Founder | 35K-User Fintech Exit | Co-Founder Snapdrum | Trained 5,000+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/L9wxapQteB8c2FpTepLA_HUx7egtLRnyuHnAGDSQc_manuuuuu.webp",
    isUpcoming: true,
    startDate: "2026-03-21T18:00:00-04:00",
    topics: ["ai-product"],
  },
  {
    id: "ll-b16d99",
    title: "AI Tools and Workflows That Actually Matter for Marketers",
    slug: "b16d99",
    instructorName: "Manu Jayawardana",
    instructorTitle: "AI Founder | 35K-User Fintech Exit | Co-Founder Snapdrum | Trained 5,000+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/Y7W4hJ5Sjq6fSu4ghsxQ_HUx7egtLRnyuHnAGDSQc_manuuuuu.webp",
    isUpcoming: true,
    startDate: "2026-03-19T18:00:00-04:00",
    topics: ["ai-productivity"],
  },
  {
    id: "ll-648b2f",
    title: "The 5 AI Tools That Actually Stick on Product Teams in 2026",
    slug: "648b2f",
    instructorName: "Aki Wijesundara, PhD",
    instructorTitle: "AI Founder | Educator | Google AI Accelerator Alum",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/byYqvIxISHCU8PvvFNu4_2XxkFVSCRcqPJa2l2mhy_aki.webp",
    isUpcoming: true,
    startDate: "2026-03-21T17:00:00-04:00",
    topics: ["ai-productivity"],
  },
  {
    id: "ll-7e73bf",
    title: "Create Your First AI Automation Without Coding in 30 Minutes",
    slug: "7e73bf",
    instructorName: "Manu Jayawardana",
    instructorTitle: "AI Founder | 35K-User Fintech Exit | Co-Founder Snapdrum | Trained 5,000+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/WOEvwVn7SNWc9fTHgkm2_HUx7egtLRnyuHnAGDSQc_manuuuuu%20(1).webp",
    isUpcoming: true,
    startDate: "2026-03-21T17:00:00-04:00",
    topics: ["ai-productivity"],
  },
  {
    id: "ll-82b290",
    title: "Build a GTM Strategy for a New Product in 30 Minutes",
    slug: "82b290",
    instructorName: "Manu Jayawardana\nName",
    instructorTitle: "AI Founder | 35K-User Fintech Exit | Co-Founder Snapdrum | Trained 5,000+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/DZx5Pmy8TWad2fenEOus_HUx7egtLRnyuHnAGDSQc_manuuuuu.webp",
    isUpcoming: true,
    startDate: "2026-03-21T18:00:00-04:00",
    topics: ["gtm-engineering"],
  },
  {
    id: "ll-0cc0d4",
    title: "Build a Simple GTM Dashboard to Track Product Adoption",
    slug: "0cc0d4",
    instructorName: "Manu Jayawardana",
    instructorTitle: "AI Founder | 35K-User Fintech Exit | Co-Founder Snapdrum | Trained 5,000+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/uLVUoXm6TBSTvbXtp1gI_HUx7egtLRnyuHnAGDSQc_manuuuuu.webp",
    isUpcoming: true,
    startDate: "2026-03-21T18:00:00-04:00",
    topics: ["gtm-engineering", "ai-x-leaders"],
  },
  {
    id: "ll-f3e6e6",
    title: "Build an AI Lead Generation Pipeline in 30 Minutes",
    slug: "f3e6e6",
    instructorName: "Manu Jayawardana",
    instructorTitle: "AI Founder | 35K-User Fintech Exit | Co-Founder Snapdrum | Trained 5,000+",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/PeG94PDTRVKLbMQl8DN7_HUx7egtLRnyuHnAGDSQc_manuuuuu.webp",
    isUpcoming: true,
    startDate: "2026-03-21T18:00:00-04:00",
    topics: ["ai-for-sales"],
  },
  {
    id: "ll-601c82",
    title: "Tuning HNSW parameters for filtered search",
    slug: "601c82",
    instructorName: "Radu Gheorghe",
    instructorTitle: "Software Engineer, Vespa.ai",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/rWnhU3ZROCu5SP2W4YCz_radu-gheorhe-2.jpg",
    isUpcoming: true,
    startDate: "2026-04-16T13:00:00-04:00",
    topics: ["rag-llm-apps"],
  },
  {
    id: "ll-d58da6",
    title: "Incrementally Adopting AI in E-Commerce Search",
    slug: "d58da6",
    instructorName: "John Berryman",
    instructorTitle: "Arcturus Labs",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/f3jqINOShCYQS9WCzGZa_image.png",
    isUpcoming: true,
    startDate: "2026-03-26T13:15:00-04:00",
    topics: ["rag-llm-apps"],
  },
  {
    id: "ll-16a850",
    title: "Break Into AI Governance. No Technical Background Required.",
    slug: "16a850",
    instructorName: "Niharika Srivastav",
    instructorTitle: "AIGP, AI Governance Advisor, Speaker, Author",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/CgVmnVevSRa9362nMzMg_Niharika%20Srivastav.jpeg",
    isUpcoming: true,
    startDate: "2026-03-20T15:00:00-04:00",
    topics: ["ai-x-leaders"],
  },
  {
    id: "ll-512087",
    title: "Automate Business & Finance w/ Claude Code, Cowork & Copilot",
    slug: "512087",
    instructorName: "Dr. Ryan Ahmed",
    instructorTitle: "Professor & AI expert | 510K+ students worldwide.",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/qgbe1Y4QBiyxQPOmvDqw_Untitled%20design.jpg",
    isUpcoming: true,
    startDate: "2026-03-19T13:00:00-04:00",
    topics: ["claude-code"],
  },
  {
    id: "ll-94d5cc",
    title: "Build Your AI Search Strategy Beyond SEO",
    slug: "94d5cc",
    instructorName: "Mostafa ElBermawy",
    instructorTitle: "Founder & CEO at Goodie AI and NoGood",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/tA7SeyafSOidfz6PISFK_Mostafa%20Profile%20image.png",
    isUpcoming: true,
    startDate: "2026-04-16T12:00:00-04:00",
    topics: ["ai-marketing"],
  },
  {
    id: "ll-85ea43",
    title: "RAG Explained: The Architecture Behind Agentic AI Systems",
    slug: "85ea43",
    instructorName: "Aishwarya Srinivasan",
    instructorTitle: "AI Entrepreneur | Ex-Google, Microsoft",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/JKsVW5XCTXeJM7DwaRet_Headshot.png",
    isUpcoming: true,
    startDate: "2026-04-04T11:00:00-04:00",
    topics: ["rag-llm-apps"],
  },
  {
    id: "ll-330bd9",
    title: "Your AI-Powered 12-Month Relationship Engine (Session 3)",
    slug: "330bd9",
    instructorName: "Matt Spangler",
    instructorTitle: "Former Compass CMO w/ over a decade in real estate tech & agent coaching",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/k7bSAfdfQcaPT5D8AsiQ_matt_smile_headshot.jpg",
    isUpcoming: true,
    startDate: "2026-03-19T12:00:00-04:00",
    topics: ["ai-for-sales"],
  },
  {
    id: "ll-167951",
    title: "Build Custom Annotation UIs for AI Evals",
    slug: "167951",
    instructorName: "Shane Butler",
    instructorTitle: "Principal Data Scientist, AI Evaluations at Ontra",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/ectoB6K6QfOiJQbSNT95_shane_headshot_edited_clean.png",
    isUpcoming: true,
    startDate: "2026-03-25T15:00:00-04:00",
    topics: ["ai-evals"],
  },
  {
    id: "ll-e698e2",
    title: "Storytelling & Presentation Building Using Claude Code",
    slug: "e698e2",
    instructorName: "Shane Butler",
    instructorTitle: "Principal Data Scientist at Ontra",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/pnYUHsaITdrgnDHhoQol_shane_butler_headshot%20(1).png",
    isUpcoming: true,
    startDate: "2026-03-27T15:00:00-04:00",
    topics: ["communication-storytelling"],
  },
  {
    id: "ll-7c6b28",
    title: "Crack Product Sense & Analytics Interviews with AI",
    slug: "7c6b28",
    instructorName: "Sravya Madipalli",
    instructorTitle: "Senior DS Leader (Ex-Microsoft)",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/USF73hADS1GqEFJhkDsJ_LinkedinProfile.jpeg",
    isUpcoming: true,
    startDate: "2026-04-10T15:00:00-04:00",
    topics: ["ai-analysis"],
  },
  {
    id: "ll-cddd45",
    title: "Measure AI Impact with Causal Inference",
    slug: "cddd45",
    instructorName: "Shane Butler",
    instructorTitle: "Principal Data Scientist, AI Evaluations at Ontra",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/8eUxIONIRhq8kMv1XaLJ_Untitled%20(2000%20x%202000%20px)%20(1).png",
    isUpcoming: true,
    startDate: "2026-04-15T13:00:00-04:00",
    topics: ["decision-making"],
  },
  {
    id: "ll-9f9c92",
    title: "Build Your First LinkedIn AI Agent (T&C Compliant)",
    slug: "9f9c92",
    instructorName: "Jacob Bank",
    instructorTitle: "Founder At Relay.App (Ex. Google, Director of PM)",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/zwpBzdXySBWA26Ccs59J_1681506751178.jpeg",
    isUpcoming: true,
    startDate: "2026-03-25T12:00:00-04:00",
    topics: ["personal-branding"],
  },
  {
    id: "ll-8085f9",
    title: "How I Use Claude Skills & Cowork for LinkedIn (Live Demo)",
    slug: "8085f9",
    instructorName: "Pietro Montaldo",
    instructorTitle: "Building practical, automated growth systems using AI | Founder @NforceAI",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/9erUmYQSTzydRRUbJuB8_1766244401161.jpeg",
    isUpcoming: true,
    startDate: "2026-04-01T12:00:00-04:00",
    topics: ["personal-branding"],
  },
  {
    id: "ll-1e1592",
    title: "Using Content to Fuel Winning Paid Media in 2026",
    slug: "1e1592",
    instructorName: "Lee Densmer",
    instructorTitle: "Content strategist and author, Content, Simplified",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/NIAS6pERkmQvFLlJclNA_Lee%20D%20headshot.jpg",
    isUpcoming: true,
    startDate: "2026-04-01T11:00:00-04:00",
    topics: ["ai-marketing"],
  },
  {
    id: "ll-d74587",
    title: "How to do Observability right?",
    slug: "d74587",
    instructorName: "Abi Aryan",
    instructorTitle: "ML Engineer with 10 years of experience in this field",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/vSVGbd5sRCOO6XsomZWW_abi-preview.png",
    isUpcoming: true,
    startDate: "2026-03-24T13:00:00-04:00",
    topics: ["ai-evals"],
  },
  {
    id: "ll-f29b69",
    title: "Design Figma Files That Scale",
    slug: "f29b69",
    instructorName: "Christine Vallaure",
    instructorTitle: "Founder moonlearning · 2× Figma Config Speaker · Awwwards Jury Member",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/pN1HDwh2TSC0dH3BDOhG_christine%20vallaure.jpg",
    isUpcoming: true,
    startDate: "2026-04-07T13:00:00-04:00",
    topics: ["figma-design-systems"],
  },
  {
    id: "ll-eb4a6e",
    title: "Achievement Design Systems - HealthTech",
    slug: "eb4a6e",
    instructorName: "John Gusiff",
    instructorTitle: "CX Strategist and Behavioral Design, Certified Make it Toolkit Instructor",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/sBRnKsBNT4SsFahUn2GJ_Gusiff%20Profile%20for%20Maven%20800%20by%20800.png",
    isUpcoming: true,
    startDate: "2026-03-31T15:00:00-04:00",
    topics: ["figma-design-systems"],
  },
  {
    id: "ll-b3de1c",
    title: "How to Build a Meeting Feedback Coach (No Coding Required)",
    slug: "b3de1c",
    instructorName: "Myles Sutholt",
    instructorTitle: "Head of Product | 10+ years building product teams",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/mMUDvjhRsyDFCLkGXPSR_4562%201000px.jpg",
    isUpcoming: true,
    startDate: "2026-03-20T12:30:00-04:00",
    topics: ["management-leadership"],
  },
  {
    id: "ll-d4f268",
    title: "Build Your First ML Model with Python and GenAI",
    slug: "d4f268",
    instructorName: "Mirza Rahim Baig",
    instructorTitle: "15+ years in AI and Data | Author & Startup Advisor  | Ex -  Zalando, Flipkart",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/08vVCIogQSaZZbB4DtXV_Rahim-Baig.jpg",
    isUpcoming: true,
    startDate: "2026-03-22T11:00:00-04:00",
    topics: ["ai-analysis"],
  },
  {
    id: "ll-75d9b9",
    title: "AEO Strategy for 2026 - Dominate AI Search (Workshop)",
    slug: "75d9b9",
    instructorName: "George Chasiotis",
    instructorTitle: "Founder at Minuttia",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/XccrtnxQGCCKyxYcTT3U_George%20Chasiotis%20B%20(Full-Color%2C%20jpg).jpg",
    isUpcoming: true,
    startDate: "2026-04-09T11:00:00-04:00",
    topics: ["ai-marketing"],
  },
  {
    id: "ll-75952b",
    title: "AI Governance & Guardrails: Setting Ethical Boundaries",
    slug: "75952b",
    instructorName: "Kathryn Kolaczek",
    instructorTitle: "Crisis Communications Strategist",
    instructorImg: "https://d2426xcxuh3ht5.cloudfront.net/aY33XaSGQYGjGkl0iEzW_Kathryn%20Headshot.jpg",
    isUpcoming: true,
    startDate: "2026-04-20T12:00:00-04:00",
    topics: ["ai-x-leaders"],
  },
];

export interface Course {
  id: string;
  name: string;
  slug: string;
  schoolSlug: string;
  instructorName: string;
  cohortDate: string | null;
  url: string;
  topics: string[];
}

export const COURSES: Course[] = [
  {
    id: "course-product-sense",
    name: "World-class Product Sense in Practice",
    slug: "product-sense",
    schoolSlug: "shreyas-doshi",
    instructorName: "Shreyas Doshi",
    cohortDate: "2026-05-02T12:00:00-04:00",
    url: "https://maven.com/shreyas-doshi/product-sense",
    topics: ["decision-making"],
  },
  {
    id: "course-evals",
    name: "AI Evals For Engineers & PMs",
    slug: "evals",
    schoolSlug: "parlance-labs",
    instructorName: "Parlance Labs",
    cohortDate: "2026-03-16T09:00:00-04:00",
    url: "https://maven.com/parlance-labs/evals",
    topics: ["ai-evals"],
  },
  {
    id: "course-ai-product-management-certification",
    name: "AI Product Management Certification",
    slug: "ai-product-management-certification",
    schoolSlug: "product-faculty",
    instructorName: "Product Faculty",
    cohortDate: "2026-04-20T12:00:00-04:00",
    url: "https://maven.com/product-faculty/ai-product-management-certification",
    topics: ["ai-evals", "ai-design"],
  },
  {
    id: "course-genai-system-design",
    name: "Building Agentic AI Applications with a Problem-First Approach",
    slug: "genai-system-design",
    schoolSlug: "aishwarya-kiriti",
    instructorName: "Aishwarya Kiriti",
    cohortDate: "2026-04-25T12:00:00-04:00",
    url: "https://maven.com/aishwarya-kiriti/genai-system-design",
    topics: ["rag-llm-apps"],
  },
  {
    id: "course-ai-pm-bootcamp",
    name: "AI Product Management Bootcamp & Certification by AI Product Academy",
    slug: "ai-pm-bootcamp",
    schoolSlug: "marily-nika",
    instructorName: "Marily Nika",
    cohortDate: "2026-03-23T12:00:00-04:00",
    url: "https://maven.com/marily-nika/ai-pm-bootcamp",
    topics: ["ai-product", "customer-research", "management-leadership"],
  },
  {
    id: "course-genaipm",
    name: "Agentic AI Product Management Certification",
    slug: "genaipm",
    schoolSlug: "mahesh-yadav",
    instructorName: "Mahesh Yadav",
    cohortDate: "2026-05-09T02:30:00-04:00",
    url: "https://maven.com/mahesh-yadav/genaipm",
    topics: ["ai-agents", "ai-evals"],
  },
  {
    id: "course-executive-communication-influence",
    name: "Executive Communication & Influence for Senior ICs and Managers",
    slug: "executive-communication-influence",
    schoolSlug: "wes-kao",
    instructorName: "Wes Kao",
    cohortDate: "2026-05-14T12:00:00-04:00",
    url: "https://maven.com/wes-kao/executive-communication-influence",
    topics: ["communication-storytelling", "management-leadership"],
  },
  {
    id: "course-scale-with-ai-agentic-workflows",
    name: "How To Scale A Business With AI & Agentic Workflows - Foundations",
    slug: "scale-with-ai-agentic-workflows",
    schoolSlug: "aibuildlab",
    instructorName: "Aibuildlab",
    cohortDate: "2026-03-30T12:00:00-04:00",
    url: "https://maven.com/aibuildlab/scale-with-ai-agentic-workflows",
    topics: ["ai-productivity"],
  },
  {
    id: "course-break-through-to-executive",
    name: "Beyond Senior Manager - Break Through to Strategic Executive",
    slug: "break-through-to-executive",
    schoolSlug: "ethan-evans",
    instructorName: "Ethan Evans",
    cohortDate: "2026-04-11T12:00:00-04:00",
    url: "https://maven.com/ethan-evans/break-through-to-executive",
    topics: ["personal-branding"],
  },
  {
    id: "course-ai-prototyping-for-product-managers",
    name: "AI Prototyping for Product Managers",
    slug: "ai-prototyping-for-product-managers",
    schoolSlug: "tech-for-product",
    instructorName: "Tech For Product",
    cohortDate: "2026-01-12T12:00:00-05:00",
    url: "https://maven.com/tech-for-product/ai-prototyping-for-product-managers",
    topics: ["vibe-coding", "claude-code"],
  },
  {
    id: "course-rag-playbook",
    name: "Systematically Improving RAG Applications",
    slug: "rag-playbook",
    schoolSlug: "applied-llms",
    instructorName: "Applied Llms",
    cohortDate: "2025-11-17T09:00:00-05:00",
    url: "https://maven.com/applied-llms/rag-playbook",
    topics: ["rag-llm-apps"],
  },
  {
    id: "course-level-up-with-figma",
    name: "Level Up with Figma",
    slug: "level-up-with-figma",
    schoolSlug: "baseline-design",
    instructorName: "Baseline Design",
    cohortDate: "2026-03-23T12:00:00-04:00",
    url: "https://maven.com/baseline-design/level-up-with-figma",
    topics: ["figma-design-systems"],
  },
  {
    id: "course-mgmt-accelerator",
    name: "MGMT Accelerator: AI-Enhanced Leadership",
    slug: "mgmt-accelerator",
    schoolSlug: "dave-kline",
    instructorName: "Dave Kline",
    cohortDate: "2026-05-05T11:00:00-04:00",
    url: "https://maven.com/dave-kline/mgmt-accelerator",
    topics: ["ai-x-leaders", "management-leadership"],
  },
  {
    id: "course-aibuilders",
    name: "Build with AI: Mindset, Habits & Tools for the Next 20 Years",
    slug: "aibuilders",
    schoolSlug: "superlinear",
    instructorName: "Superlinear",
    cohortDate: "2026-04-13T12:00:00-04:00",
    url: "https://maven.com/superlinear/aibuilders",
    topics: ["ai-productivity"],
  },
  {
    id: "course-cracking-the-c-suite",
    name: "Cracking the C-suite in the AI Economy",
    slug: "cracking-the-c-suite",
    schoolSlug: "ethan-evans",
    instructorName: "Ethan Evans",
    cohortDate: "2026-05-02T13:00:00-04:00",
    url: "https://maven.com/ethan-evans/cracking-the-c-suite",
    topics: ["personal-branding"],
  },
  {
    id: "course-abtesting",
    name: "Accelerating Innovation with A/B Testing",
    slug: "abtesting",
    schoolSlug: "kohavi",
    instructorName: "Kohavi",
    cohortDate: "2026-06-01T12:00:00-04:00",
    url: "https://maven.com/kohavi/abtesting",
    topics: ["decision-making"],
  },
  {
    id: "course-ai-product-management",
    name: "AI Product Management 101 & Certification - Building AI Products end-to-end",
    slug: "ai-product-management",
    schoolSlug: "marily-nika",
    instructorName: "Marily Nika",
    cohortDate: "2026-03-23T06:00:00-04:00",
    url: "https://maven.com/marily-nika/ai-product-management",
    topics: ["customer-research"],
  },
  {
    id: "course-ai-product-strategy-certificate",
    name: "AI Product Strategy Certificate for Leaders",
    slug: "ai-product-strategy-certificate",
    schoolSlug: "product-faculty",
    instructorName: "Product Faculty",
    cohortDate: "2026-04-20T12:00:00-04:00",
    url: "https://maven.com/product-faculty/ai-product-strategy-certificate",
    topics: ["ai-product"],
  },
  {
    id: "course-make-better-decisions",
    name: "Make Better Decisions",
    slug: "make-better-decisions",
    schoolSlug: "annie-duke",
    instructorName: "Annie Duke",
    cohortDate: "2026-04-20T16:00:00-04:00",
    url: "https://maven.com/annie-duke/make-better-decisions",
    topics: ["decision-making"],
  },
  {
    id: "course-mxdai",
    name: "Master UX Design for AI",
    slug: "mxdai",
    schoolSlug: "hcaiinstitute",
    instructorName: "Hcaiinstitute",
    cohortDate: "2026-03-23T03:00:00-04:00",
    url: "https://maven.com/hcaiinstitute/mxdai",
    topics: ["ux-design", "ai-design"],
  },
  {
    id: "course-advanced-ai-product-management",
    name: "Advanced AI Product Leadership Certification",
    slug: "advanced-ai-product-management",
    schoolSlug: "marily-nika",
    instructorName: "Marily Nika",
    cohortDate: "2026-04-13T05:00:00-04:00",
    url: "https://maven.com/marily-nika/advanced-ai-product-management",
    topics: ["ai-product", "ai-x-leaders", "customer-research"],
  },
  {
    id: "course-ai-build-lab",
    name: "Master Market-Ready Agentic AI Workflows: Step-by-Step, No Code Required",
    slug: "ai-build-lab",
    schoolSlug: "aibuildlab",
    instructorName: "Aibuildlab",
    cohortDate: "2026-01-19T06:00:00-05:00",
    url: "https://maven.com/aibuildlab/ai-build-lab",
    topics: ["ai-productivity"],
  },
  {
    id: "course-prototyping-with-ai",
    name: "Prototyping with AI Bootcamp",
    slug: "prototyping-with-ai",
    schoolSlug: "no-code-ai",
    instructorName: "No Code Ai",
    cohortDate: "2026-04-06T14:30:00-04:00",
    url: "https://maven.com/no-code-ai/prototyping-with-ai",
    topics: ["vibe-coding"],
  },
  {
    id: "course-design-system-bootcamp",
    name: "Design System Bootcamp",
    slug: "design-system-bootcamp",
    schoolSlug: "ui-prep",
    instructorName: "Ui Prep",
    cohortDate: "2025-10-20T02:15:00-04:00",
    url: "https://maven.com/ui-prep/design-system-bootcamp",
    topics: ["figma-design-systems"],
  },
  {
    id: "course-hands-on-ai-for-leaders",
    name: "Hands-on Agentic AI for Leaders",
    slug: "hands-on-ai-for-leaders",
    schoolSlug: "james-gray",
    instructorName: "James Gray",
    cohortDate: "2026-04-06T08:00:00-04:00",
    url: "https://maven.com/james-gray/hands-on-ai-for-leaders",
    topics: ["claude-code"],
  },
  {
    id: "course-rapid-ai-traction-for-senior-leadership-teams-25april",
    name: "Rapid AI Traction for Senior Leadership Teams",
    slug: "rapid-ai-traction-for-senior-leadership-teams-25april",
    schoolSlug: "ten-past-tomorrow",
    instructorName: "Ten Past Tomorrow",
    cohortDate: "2026-04-05T17:00:00-04:00",
    url: "https://maven.com/ten-past-tomorrow/rapid-ai-traction-for-senior-leadership-teams-25april",
    topics: ["ai-x-leaders"],
  },
  {
    id: "course-aidesign",
    name: "Become an AI Product Designer",
    slug: "aidesign",
    schoolSlug: "maheensohail",
    instructorName: "Maheensohail",
    cohortDate: "2026-08-17T23:00:00-04:00",
    url: "https://maven.com/maheensohail/aidesign",
    topics: ["ai-design"],
  },
  {
    id: "course-vibe-code-your-next-side-project",
    name: "Vibe Code Production-Ready Side Projects",
    slug: "vibe-code-your-next-side-project",
    schoolSlug: "tech-for-product",
    instructorName: "Tech For Product",
    cohortDate: "2026-01-12T12:00:00-05:00",
    url: "https://maven.com/tech-for-product/vibe-code-your-next-side-project",
    topics: ["vibe-coding", "claude-code"],
  },
  {
    id: "course-ai-powered-people-management",
    name: "How to Become a Supermanager with AI",
    slug: "ai-powered-people-management",
    schoolSlug: "hilary-gridley",
    instructorName: "Hilary Gridley",
    cohortDate: "2026-03-10T10:00:00-04:00",
    url: "https://maven.com/hilary-gridley/ai-powered-people-management",
    topics: ["ai-productivity"],
  },
  {
    id: "course-build-ai-product-sense",
    name: "Build AI Product Sense",
    slug: "build-ai-product-sense",
    schoolSlug: "aman-khan",
    instructorName: "Aman Khan",
    cohortDate: "2026-04-18T12:00:00-04:00",
    url: "https://maven.com/aman-khan/build-ai-product-sense",
    topics: ["ai-product"],
  },
  {
    id: "course-ai-for-real-estate",
    name: "The AI Marketing System for Top Real Estate Agents",
    slug: "ai-for-real-estate",
    schoolSlug: "matt-spangler",
    instructorName: "Matt Spangler",
    cohortDate: "2026-03-23T15:00:00-04:00",
    url: "https://maven.com/matt-spangler/ai-for-real-estate",
    topics: ["ai-marketing"],
  },
  {
    id: "course-mgmt-fundamentals",
    name: "MGMT Fundamentals - Foundational Skills for New Managers",
    slug: "mgmt-fundamentals",
    schoolSlug: "dave-kline",
    instructorName: "Dave Kline",
    cohortDate: "2026-04-21T12:00:00-04:00",
    url: "https://maven.com/dave-kline/mgmt-fundamentals",
    topics: ["ai-x-leaders"],
  },
  {
    id: "course-end-to-end-ai-engineering",
    name: "End-to-End AI Engineering Bootcamp",
    slug: "end-to-end-ai-engineering",
    schoolSlug: "swirl-ai",
    instructorName: "Swirl Ai",
    cohortDate: "2026-03-23T06:00:00-04:00",
    url: "https://maven.com/swirl-ai/end-to-end-ai-engineering",
    topics: ["rag-llm-apps"],
  },
  {
    id: "course-ai-skills-for-research",
    name: "AI for Customer Research: Future-Proof Your UX & Product Skills",
    slug: "ai-skills-for-research",
    schoolSlug: "john-whalen",
    instructorName: "John Whalen",
    cohortDate: "2026-04-14T19:00:00-04:00",
    url: "https://maven.com/john-whalen/ai-skills-for-research",
    topics: ["customer-research"],
  },
  {
    id: "course-ai-powered-search",
    name: "AI-Powered Search: Modern Retrieval for Humans & Agents",
    slug: "ai-powered-search",
    schoolSlug: "search-school",
    instructorName: "Search School",
    cohortDate: "2026-03-05T12:00:00-05:00",
    url: "https://maven.com/search-school/ai-powered-search",
    topics: ["rag-llm-apps"],
  },
  {
    id: "course-executive-presence-influence",
    name: "Stronger Executive Presence:  Be Visible, Gain Influence, & Drive Your Career",
    slug: "executive-presence-influence",
    schoolSlug: "ethan-evans",
    instructorName: "Ethan Evans",
    cohortDate: "2026-04-18T12:00:00-04:00",
    url: "https://maven.com/ethan-evans/executive-presence-influence",
    topics: ["communication-storytelling", "personal-branding"],
  },
  {
    id: "course-modern-forecasting",
    name: "Modern Forecasting in Practice",
    slug: "modern-forecasting",
    schoolSlug: "tim-januschowski",
    instructorName: "Tim Januschowski",
    cohortDate: "2026-01-12T12:00:00-05:00",
    url: "https://maven.com/tim-januschowski/modern-forecasting",
    topics: ["ai-analysis"],
  },
  {
    id: "course-advanced-ab",
    name: "Advanced Topics in Practical A/B Testing",
    slug: "advanced-ab",
    schoolSlug: "kohavi",
    instructorName: "Kohavi",
    cohortDate: "2026-03-23T12:00:00-04:00",
    url: "https://maven.com/kohavi/advanced-ab",
    topics: ["decision-making"],
  },
  {
    id: "course-claude-code-for-product-managers",
    name: "Claude Code for Product Managers",
    slug: "claude-code-for-product-managers",
    schoolSlug: "aman-khan",
    instructorName: "Aman Khan",
    cohortDate: "2026-03-16T17:00:00-04:00",
    url: "https://maven.com/aman-khan/claude-code-for-product-managers",
    topics: ["claude-code"],
  },
  {
    id: "course-from-rag-to-agents",
    name: "AI Engineering Buildcamp: From RAG to Agents",
    slug: "from-rag-to-agents",
    schoolSlug: "alexey-grigorev",
    instructorName: "Alexey Grigorev",
    cohortDate: "2026-04-13T11:00:00-04:00",
    url: "https://maven.com/alexey-grigorev/from-rag-to-agents",
    topics: ["ai-agents", "rag-llm-apps"],
  },
];

export function getForVertical(vertical: Vertical) {
  const topics = VERTICAL_TO_TOPICS[vertical];
  const lessons = LESSONS.filter(l => l.topics.some(t => topics.includes(t)));
  const courses = COURSES.filter(c => c.topics.some(t => topics.includes(t)));
  return { lessons, courses };
}
